import Tort from '../assets/icons/tort_icon.png'
import {
  torty1,
  torty2,
  torty3,
  torty4,
  torty5,
  torty6,
  torty7,
  torty8,
  torty9,
  torty10,
  torty11,
  torty12,
  torty13,
  torty14,
  torty15,
  torty16,
  torty17,
  torty18,
  torty19,
  torty20,
  torty21,
  torty22,
  torty23,
  torty24,
  torty25,
  torty26,
  torty27,
  torty28,
  torty29,
  torty30,
  torty31,
  torty32,
  torty33,
} from '@/assets/images/gallery/torty/torty.ts'
import {
  bento1,
  bento2,
  bento3,
  bento4,
  bento5,
  bento6,
  bento7,
  bento8,
  bento9,
  bento10,
  bento11,
  bento12,
  bento13,
  bento14,
  bento15,
  bento16,
  bento17,
  bento18,
  bento19,
  bento20,
} from '@/assets/images/gallery/bento/bento.ts'
import {
  mochi1,
  mochi2,
  mochi3,
  mochi4,
  mochi5,
  mochi6,
  mochi7,
  mochi8,
  mochi9,
  mochi10,
  mochi11,
  mochi12,
  mochi13,
  mochi14,
  mochi15,
  mochi16,
  mochi17,
  mochi18,
  mochi19,
  mochi20,
  mochi21,
} from '@/assets/images/gallery/mochi/mochi.ts'
import { pawlowa1 } from '@/assets/images/gallery/pawlowa/pawlowa.ts'
import { inny1, inny2, inny3 } from '@/assets/images/gallery/inny/inny.ts'

export const products = [
  {
    id: 1,
    title: 'Torty',
    image:
      'https://res.cloudinary.com/dzfvnm3it/image/upload/f_auto,q_auto/v1/cukiernia-pavlova/oferta/of1',
    description:
      'Najlepsze i najsmaczniejsze torty tylko u nas! W naszej pracowni wypiekamy wyjątkowe torty na każdą okazję – od eleganckich weselnych arcydzieł po urocze torty urodzinowe z ulubionymi postaciami dla dzieci. Stawiamy na jakość i smak, dlatego używamy wyłącznie naturalnych składników i świeżych owoców. Zamów tort, który zachwyci wyglądem i smakiem!',
    gallery: [
      torty1,
      torty2,
      torty3,
      torty4,
      torty5,
      torty6,
      torty7,
      torty8,
      torty9,
      torty10,
      torty11,
      torty12,
      torty13,
      torty14,
      torty15,
      torty16,
      torty17,
      torty18,
      torty19,
      torty20,
      torty21,
      torty22,
      torty23,
      torty24,
      torty25,
      torty26,
      torty27,
      torty28,
      torty29,
      torty30,
      torty31,
      torty32,
      torty33,
    ],
  },
  {
    id: 2,
    title: 'Bento-tort',
    image:
      'https://res.cloudinary.com/dzfvnm3it/image/upload/f_auto,q_auto/v1/cukiernia-pavlova/oferta/of2',
    description:
      'Bento torty – małe dzieła sztuki w pudełku! Bento torty to stylowe i kompaktowe torciki, które przywędrowały do nas z Korei. Charakteryzują się niewielkim rozmiarem, lekkością i delikatnym smakiem. Te desery stały się prawdziwym trendem dzięki minimalistycznemu designowi, indywidualnym dekoracjom i wygodnemu formatowi – łatwo je zabrać ze sobą lub podarować bliskiej osobie. Przygotowujemy bento torty z naturalnych składników, tworząc puszyste biszkopty i aksamitne kremy. Możesz wybrać klasyczne smaki lub spróbować czegoś wyjątkowego. Nasze mini torciki są idealne na każdą okazję: urodziny, wyznanie miłości lub po prostu jako słodka niespodzianka bez powodu! Zamów bento tort – małą radość w pięknym pudełku!',
    gallery: [
      bento1,
      bento2,
      bento3,
      bento4,
      bento5,
      bento6,
      bento7,
      bento8,
      bento9,
      bento10,
      bento11,
      bento12,
      bento13,
      bento14,
      bento15,
      bento16,
      bento17,
      bento18,
      bento19,
      bento20,
    ],
  },
  {
    id: 3,
    title: 'Mochi',
    image:
      'https://res.cloudinary.com/dzfvnm3it/image/upload/f_auto,q_auto/v1/cukiernia-pavlova/oferta/of3',
    description:
      'Mochi – tradycyjny japoński przysmak. Mochi to delikatne i elastyczne ciasteczka ryżowe, przygotowywane z kleistego ryżu. Ich historia sięga setek lat, a w Japonii symbolizują one szczęście i pomyślność. Dziś mochi zdobyły popularność na całym świecie dzięki swojemu niezwykłemu smakowi i różnorodnym nadzieniom – od klasycznej pasty z czerwonej fasoli po owocowe i kremowe wypełnienia. Przygotowujemy mochi według tradycyjnych receptur, używając wyłącznie naturalnych składników. W naszej ofercie znajdziesz mochi na każdy gust: z delikatnym kremowym nadzieniem, owocami i aromatycznymi orzechami. To idealny deser na specjalne okazje lub po prostu, by sprawić sobie i bliskim słodką przyjemność. Spróbuj prawdziwych mochi – zasmakuj w orientalnej słodyczy!',
    gallery: [
      mochi1,
      mochi2,
      mochi3,
      mochi4,
      mochi5,
      mochi6,
      mochi7,
      mochi8,
      mochi9,
      mochi10,
      mochi11,
      mochi12,
      mochi13,
      mochi14,
      mochi15,
      mochi16,
      mochi17,
      mochi18,
      mochi19,
      mochi20,
      mochi21,
    ],
  },
  {
    id: 4,
    title: 'Beza Pawlowa',
    image:
      'https://res.cloudinary.com/dzfvnm3it/image/upload/f_auto,q_auto/v1/cukiernia-pavlova/oferta/of6',
    description:
      'Pavlova – lekka rozkosz w każdym kęsie! Deser Pavlova to delikatna chmurka z chrupiącej bezy o miękkim wnętrzu, udekorowana lekkim kremem i świeżymi owocami. Ten kultowy deser, stworzony na cześć baletnicy Anny Pawłowej, zachwyca swoją puszystą strukturą i idealnym balansem smaków. Przygotowujemy ten deser według klasycznych receptur, używając wyłącznie naturalnych składników. Chrupiąca skorupka, aksamitny krem i soczyste owoce tworzą doskonałe połączenie. Pavlova to elegancki deser na wyjątkowe okazje lub po prostu na chwilę słodkiej przyjemności. Spróbuj legendarnego deseru – lekkość i smak w każdej łyżeczce!',
    gallery: [pawlowa1],
  },
  {
    id: 5,
    title: 'Inny',
    image:
      'https://res.cloudinary.com/dzfvnm3it/image/upload/f_auto,q_auto/v1/cukiernia-pavlova/oferta/of4',
    description:
      'Zimny sernik na patyku – lody o wyrafinowanym smaku! Przedstawiamy nową wersję ulubionego deseru – zimny sernik w formie lodów! Delikatna serowa konsystencja, chrupiący spód i polewa z czekolady lub owocowego purée zamieniają ten deser w prawdziwą rozkosz. To idealne połączenie kremowego smaku i orzeźwiającej lekkości. Przygotowujemy nasze serniki wyłącznie z naturalnych składników, tworząc deser, który rozpływa się w ustach. Zimny sernik na patyku to doskonały przysmak na upalny dzień, wyjątkową okazję lub po prostu dla przyjemności! Oprócz serników oferujemy również tradycyjne domowe wypieki – pyszne, aromatyczne pierogi, kruche domowe ciasteczka oraz wyjątkowe, świąteczne paschy. Wszystkie nasze produkty przygotowujemy wyłącznie z naturalnych składników, aby zapewnić najwyższą jakość i niezapomniany smak. Spróbuj sernika w nowej odsłonie i odkryj smak domowych wypieków – naturalnych, pełnych pasji i miłości do tradycyjnej kuchni!',
    gallery: [inny1, inny2, inny3],
  },
]

export const features = [
  { icon: Tort, text: 'Szeroki wybór ciast' },
  { icon: Tort, text: 'Świeże składniki' },
  { icon: Tort, text: 'Najwyższa jakość' },
  { icon: Tort, text: 'Sprawdzony przypisy' },
]

export const gallery = [
  'https://res.cloudinary.com/dzfvnm3it/image/upload/f_auto,q_auto/v1/cukiernia-pavlova/gallery/1',
  'https://res.cloudinary.com/dzfvnm3it/image/upload/f_auto,q_auto/v1/cukiernia-pavlova/gallery/2',
  'https://res.cloudinary.com/dzfvnm3it/image/upload/f_auto,q_auto/v1/cukiernia-pavlova/gallery/3',
  'https://res.cloudinary.com/dzfvnm3it/image/upload/f_auto,q_auto/v1/cukiernia-pavlova/gallery/4',
  'https://res.cloudinary.com/dzfvnm3it/image/upload/f_auto,q_auto/v1/cukiernia-pavlova/gallery/5',
  'https://res.cloudinary.com/dzfvnm3it/image/upload/f_auto,q_auto/v1/cukiernia-pavlova/gallery/6',
  'https://res.cloudinary.com/dzfvnm3it/image/upload/f_auto,q_auto/v1/cukiernia-pavlova/gallery/7',
  'https://res.cloudinary.com/dzfvnm3it/image/upload/f_auto,q_auto/v1/cukiernia-pavlova/gallery/8',
]
